rtl8812au: Fix builds with kernel 5.12
Changes due to kernel commit 1d11fa696733 ("net-gro: remove GRO_DROP")

Fixes the following build error:

out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/linux/recv_linux.c:337:55:
error: 'GRO_DROP' undeclared (first use in this function)
    if (rtw_napi_gro_receive(&padapter->napi, pskb) != GRO_DROP)