wl: add patch for kernel 5.6
Android.mk is modified to apply incremental patch 011-linux560.patch
which uses ioremap() instead of ioremap_nocache() for kernel 5.6 and later,
thus avoiding following building errors:

~/pie-x86_kernel/out/target/product/x86_64/obj/kmodule/wl/src/shared/linux_osl.c:949:2:
error: implicit declaration of function 'ioremap_nocache' [-Werror=implicit-function-declaration]
...
~/pie-x86_kernel/out/target/product/x86_64/obj/kmodule/wl/src/wl/sys/wl_linux.c:589:2:
error: implicit declaration of function 'ioremap_nocache' [-Werror=implicit-function-declaration]
...
/pie-x86_kernel/out/target/product/x86_64/obj/kmodule/wl/src/wl/sys/wl_linux.c:779:15:
warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
cc1: some warnings being treated as errors

NOTE: changes due to 4bdc0d6 ("remove ioremap_nocache and devm_ioremap_nocache")