wl: add patch for kernel 5.1
Android.mk is modified to apply incremental patch linux-510.patch
which implements the use of set_fs(KERNEL_DS) instead of set_fs(get_ds())
for kernel 5.1 and later, thus avoiding following error:

error: implicit declaration of function 'get_ds'